name: hacktheplanet2

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: hackthebox api request - achievement_graph endpoint
        run: |          
          response=$(curl --location 'https://www.hackthebox.com/api/v4/profile/graph/1Y/1190029' -H "Authorization: Bearer ${{ secrets.HTB_TOKEN }}" -s)
          echo $response

      - name: Run a multi-line script
        run: |
          echo hacktheplanet!
          echo hacktheplanet!hacktheplanet!
