name: hacktheplanet2

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install jq
        run: sudo apt-get install -y jq


      - name: Install Dependencies
        run: |
          pip install -r scripts/requirements.txt
          
      - name: hackthebox api request - achievement_graph endpoint
        run: |          
          response=$(curl --location 'https://www.hackthebox.com/api/v4/profile/graph/1Y/1190029' -H "Authorization: Bearer ${{ secrets.HTB_TOKEN }}" -s)
          echo $response
          escaped_response=$(echo $response | jq -c '.')
          echo "RESPONSE=$escaped_response" >> $GITHUB_ENV
          
      - name: exec graph_gen.py script
        run: |
          echo hacktheplanet!
          python scripts/graph_gen.py "${{ env.RESPONSE }}"
